% Facilidad para hacer negocios

facilidad_de_hacer_negocios(mexico,47).
facilidad_de_hacer_negocios(peru,54).
facilidad_de_hacer_negocios(colombia,53).
facilidad_de_hacer_negocios(puertorico,55).
facilidad_de_hacer_negocios(jamaica,67).
facilidad_de_hacer_negocios(costarica,62).
facilidad_de_hacer_negocios(panama,70).
facilidad_de_hacer_negocios(guatemala,88).
facilidad_de_hacer_negocios(santalucia,86).
facilidad_de_hacer_negocios(uruguay,90).
facilidad_de_hacer_negocios(elsalvador,95).
facilidad_de_hacer_negocios(trinidadytobago,96).
facilidad_de_hacer_negocios(republicadominicana,103).
facilidad_de_hacer_negocios(dominica,101).
facilidad_de_hacer_negocios(paraguay,106).
facilidad_de_hacer_negocios(honduras,105).
facilidad_de_hacer_negocios(ecuador,114).
facilidad_de_hacer_negocios(argentina,116).
facilidad_de_hacer_negocios(antiguaybarbuda,113).
facilidad_de_hacer_negocios(belice,112).
facilidad_de_hacer_negocios(barbados,117).
facilidad_de_hacer_negocios(brasil,123).
facilidad_de_hacer_negocios(guyana,124).
facilidad_de_hacer_negocios(nicaragua,127).
facilidad_de_hacer_negocios(bahamas,121).
facilidad_de_hacer_negocios(sanvicenteylasgranadinas,125).
facilidad_de_hacer_negocios(sankittsynevis,134).
facilidad_de_hacer_negocios(grenada,138).
facilidad_de_hacer_negocios(bolivia,149).
facilidad_de_hacer_negocios(suriname,158).
facilidad_de_hacer_negocios(haiti,181).
facilidad_de_hacer_negocios(venezuela,187).

% Comparacion filtrada

comparacion_filtrada(mexico,1).
comparacion_filtrada(peru,2).
comparacion_filtrada(colombia,3).
comparacion_filtrada(puertorico,4).
comparacion_filtrada(jamaica,5).
comparacion_filtrada(costarica,6).
comparacion_filtrada(panama,7).
comparacion_filtrada(guatemala,8).
comparacion_filtrada(santalucia,9).
comparacion_filtrada(uruguay,10).
comparacion_filtrada(elsalvador,11).
comparacion_filtrada(trinidadytobago,12).
comparacion_filtrada(republicadominicana,13).
comparacion_filtrada(dominica,14).
comparacion_filtrada(paraguay,15).
comparacion_filtrada(honduras,16).
comparacion_filtrada(ecuador,17).
comparacion_filtrada(argentina,18).
comparacion_filtrada(antiguaybarbuda,19).
comparacion_filtrada(belice,20).
comparacion_filtrada(barbados,21).
comparacion_filtrada(brasil,22).
comparacion_filtrada(guyana,23).
comparacion_filtrada(nicaragua,24).
comparacion_filtrada(bahamas,25).
comparacion_filtrada(sanvicenteylasgranadinas,26).
comparacion_filtrada(sankittsynevis,27).
comparacion_filtrada(grenada,28).
comparacion_filtrada(bolivia,29).
comparacion_filtrada(suriname,30).
comparacion_filtrada(haiti,31).
comparacion_filtrada(venezuela,32).

% Apertura de un negocio

apertura_de_un_negocio(mexico,12).
apertura_de_un_negocio(peru,15).
apertura_de_un_negocio(colombia,5).
apertura_de_un_negocio(puertorico,3).
apertura_de_un_negocio(jamaica,1).
apertura_de_un_negocio(costarica,20).
apertura_de_un_negocio(panama,2).
apertura_de_un_negocio(guatemala,18).
apertura_de_un_negocio(santalucia,7).
apertura_de_un_negocio(uruguay,4).
apertura_de_un_negocio(elsalvador,22).
apertura_de_un_negocio(trinidadytobago,8).
apertura_de_un_negocio(republicadominicana,16).
apertura_de_un_negocio(dominica,6).
apertura_de_un_negocio(paraguay,23).
apertura_de_un_negocio(honduras,24).
apertura_de_un_negocio(ecuador,27).
apertura_de_un_negocio(argentina,25).
apertura_de_un_negocio(antiguaybarbuda,19).
apertura_de_un_negocio(belice,26).
apertura_de_un_negocio(barbados,14).
apertura_de_un_negocio(brasil,28).
apertura_de_un_negocio(guyana,13).
apertura_de_un_negocio(nicaragua,21).
apertura_de_un_negocio(bahamas,17).
apertura_de_un_negocio(sanvicenteylasgranadinas,10).
apertura_de_un_negocio(sankittsynevis,11).
apertura_de_un_negocio(grenada,9).
apertura_de_un_negocio(bolivia,29).
apertura_de_un_negocio(suriname,30).
apertura_de_un_negocio(haiti,31).
apertura_de_un_negocio(venezuela,32).

% Manejo de permisos de construccion

manejo_de_permisos_de_construccion(mexico,12).
manejo_de_permisos_de_construccion(peru,4).
manejo_de_permisos_de_construccion(colombia,1).
manejo_de_permisos_de_construccion(puertorico,21).
manejo_de_permisos_de_construccion(jamaica,10).
manejo_de_permisos_de_construccion(costarica,5).
manejo_de_permisos_de_construccion(panama,9).
manejo_de_permisos_de_construccion(guatemala,14).
manejo_de_permisos_de_construccion(santalucia,6).
manejo_de_permisos_de_construccion(uruguay,28).
manejo_de_permisos_de_construccion(elsalvador,26).
manejo_de_permisos_de_construccion(trinidadytobago,24).
manejo_de_permisos_de_construccion(republicadominicana,3).
manejo_de_permisos_de_construccion(dominica,15).
manejo_de_permisos_de_construccion(paraguay,8).
manejo_de_permisos_de_construccion(honduras,13).
manejo_de_permisos_de_construccion(ecuador,11).
manejo_de_permisos_de_construccion(argentina,32).
manejo_de_permisos_de_construccion(antiguaybarbuda,18).
manejo_de_permisos_de_construccion(belice,16).
manejo_de_permisos_de_construccion(barbados,27).
manejo_de_permisos_de_construccion(brasil,31).
manejo_de_permisos_de_construccion(guyana,23).
manejo_de_permisos_de_construccion(nicaragua,30).
manejo_de_permisos_de_construccion(bahamas,19).
manejo_de_permisos_de_construccion(sanvicenteylasgranadinas,7).
manejo_de_permisos_de_construccion(sankittsynevis,2).
manejo_de_permisos_de_construccion(grenada,17).
manejo_de_permisos_de_construccion(bolivia,25).
manejo_de_permisos_de_construccion(suriname,20).
manejo_de_permisos_de_construccion(haiti,29).
manejo_de_permisos_de_construccion(venezuela,22).

% Cumplimiento de contratos

cumplimiento_de_contratos(mexico,3).
cumplimiento_de_contratos(peru,7).
cumplimiento_de_contratos(colombia,31).
cumplimiento_de_contratos(puertorico,16).
cumplimiento_de_contratos(jamaica,19).
cumplimiento_de_contratos(costarica,21).
cumplimiento_de_contratos(panama,26).
cumplimiento_de_contratos(guatemala,30).
cumplimiento_de_contratos(santalucia,8).
cumplimiento_de_contratos(uruguay,18).
cumplimiento_de_contratos(elsalvador,17).
cumplimiento_de_contratos(trinidadytobago,29).
cumplimiento_de_contratos(republicadominicana,23).
cumplimiento_de_contratos(dominica,12).
cumplimiento_de_contratos(paraguay,9).
cumplimiento_de_contratos(honduras,27).
cumplimiento_de_contratos(ecuador,15).
cumplimiento_de_contratos(argentina,5).
cumplimiento_de_contratos(antiguaybarbuda,1).
cumplimiento_de_contratos(belice,24).
cumplimiento_de_contratos(barbados,28).
cumplimiento_de_contratos(brasil,2).
cumplimiento_de_contratos(guyana,14).
cumplimiento_de_contratos(nicaragua,13).
cumplimiento_de_contratos(bahamas,10).
cumplimiento_de_contratos(sanvicenteylasgranadinas,6).
cumplimiento_de_contratos(sankittsynevis,4).
cumplimiento_de_contratos(grenada,11).
cumplimiento_de_contratos(bolivia,22).
cumplimiento_de_contratos(suriname,32).
cumplimiento_de_contratos(haiti,20).
cumplimiento_de_contratos(venezuela,25).

% Obtencion de electricidad

obtencion_de_electricidad(mexico,21).
obtencion_de_electricidad(peru,10).
obtencion_de_electricidad(colombia,13).
obtencion_de_electricidad(puertorico,11).
obtencion_de_electricidad(jamaica,24).
obtencion_de_electricidad(costarica,3).
obtencion_de_electricidad(panama,2).
obtencion_de_electricidad(guatemala,1).
obtencion_de_electricidad(santalucia,8).
obtencion_de_electricidad(uruguay,6).
obtencion_de_electricidad(elsalvador,26).
obtencion_de_electricidad(trinidadytobago,4).
obtencion_de_electricidad(republicadominicana,31).
obtencion_de_electricidad(dominica,9).
obtencion_de_electricidad(paraguay,25).
obtencion_de_electricidad(honduras,30).
obtencion_de_electricidad(ecuador,20).
obtencion_de_electricidad(argentina,18).
obtencion_de_electricidad(antiguaybarbuda,5).
obtencion_de_electricidad(belice,14).
obtencion_de_electricidad(barbados,19).
obtencion_de_electricidad(brasil,7).
obtencion_de_electricidad(guyana,28).
obtencion_de_electricidad(nicaragua,23).
obtencion_de_electricidad(bahamas,27).
obtencion_de_electricidad(sanvicenteylasgranadinas,16).
obtencion_de_electricidad(sankittsynevis,17).
obtencion_de_electricidad(grenada,12).
obtencion_de_electricidad(bolivia,22).
obtencion_de_electricidad(suriname,15).
obtencion_de_electricidad(haiti,29).
obtencion_de_electricidad(venezuela,32).

% Registro de propiedades

registro_de_propiedades(mexico,11).
registro_de_propiedades(peru,1).
registro_de_propiedades(colombia,3).
registro_de_propiedades(puertorico,26).
registro_de_propiedades(jamaica,16).
registro_de_propiedades(costarica,2).
registro_de_propiedades(panama,9).
registro_de_propiedades(guatemala,6).
registro_de_propiedades(santalucia,12).
registro_de_propiedades(uruguay,13).
registro_de_propiedades(elsalvador,5).
registro_de_propiedades(trinidadytobago,24).
registro_de_propiedades(republicadominicana,8).
registro_de_propiedades(dominica,27).
registro_de_propiedades(paraguay,7).
registro_de_propiedades(honduras,10).
registro_de_propiedades(ecuador,4).
registro_de_propiedades(argentina,14).
registro_de_propiedades(antiguaybarbuda,25).
registro_de_propiedades(belice,17).
registro_de_propiedades(barbados,20).
registro_de_propiedades(brasil,18).
registro_de_propiedades(guyana,15).
registro_de_propiedades(nicaragua,23).
registro_de_propiedades(bahamas,29).
registro_de_propiedades(sanvicenteylasgranadinas,28).
registro_de_propiedades(sankittsynevis,32).
registro_de_propiedades(grenada,21).
registro_de_propiedades(bolivia,22).
registro_de_propiedades(suriname,30).
registro_de_propiedades(haiti,31).
registro_de_propiedades(venezuela,19).

% Obtencion de credito

obtencion_de_credito(mexico,2).
obtencion_de_credito(peru,6).
obtencion_de_credito(colombia,1).
obtencion_de_credito(puertorico,5).
obtencion_de_credito(jamaica,8).
obtencion_de_credito(costarica,4).
obtencion_de_credito(panama,9).
obtencion_de_credito(guatemala,7).
obtencion_de_credito(santalucia,27).
obtencion_de_credito(uruguay,12).
obtencion_de_credito(elsalvador,10).
obtencion_de_credito(trinidadytobago,11).
obtencion_de_credito(republicadominicana,16).
obtencion_de_credito(dominica,24).
obtencion_de_credito(paraguay,18).
obtencion_de_credito(honduras,3).
obtencion_de_credito(ecuador,17).
obtencion_de_credito(argentina,14).
obtencion_de_credito(antiguaybarbuda,28).
obtencion_de_credito(belice,30).
obtencion_de_credito(barbados,21).
obtencion_de_credito(brasil,15).
obtencion_de_credito(guyana,13).
obtencion_de_credito(nicaragua,19).
obtencion_de_credito(bahamas,23).
obtencion_de_credito(sanvicenteylasgranadinas,29).
obtencion_de_credito(sankittsynevis,26).
obtencion_de_credito(grenada,25).
obtencion_de_credito(bolivia,22).
obtencion_de_credito(suriname,32).
obtencion_de_credito(haiti,31).
obtencion_de_credito(venezuela,20).

% Proteccion de los inversionistas minoritarios

proteccion_de_los_inversionistas_minoritarios(mexico,4).
proteccion_de_los_inversionistas_minoritarios(peru,6).
proteccion_de_los_inversionistas_minoritarios(colombia,1).
proteccion_de_los_inversionistas_minoritarios(puertorico,10).
proteccion_de_los_inversionistas_minoritarios(jamaica,7).
proteccion_de_los_inversionistas_minoritarios(costarica,29).
proteccion_de_los_inversionistas_minoritarios(panama,9).
proteccion_de_los_inversionistas_minoritarios(guatemala,30).
proteccion_de_los_inversionistas_minoritarios(santalucia,14).
proteccion_de_los_inversionistas_minoritarios(uruguay,21).
proteccion_de_los_inversionistas_minoritarios(elsalvador,26).
proteccion_de_los_inversionistas_minoritarios(trinidadytobago,5).
proteccion_de_los_inversionistas_minoritarios(republicadominicana,12).
proteccion_de_los_inversionistas_minoritarios(dominica,8).
proteccion_de_los_inversionistas_minoritarios(paraguay,24).
proteccion_de_los_inversionistas_minoritarios(honduras,22).
proteccion_de_los_inversionistas_minoritarios(ecuador,19).
proteccion_de_los_inversionistas_minoritarios(argentina,3).
proteccion_de_los_inversionistas_minoritarios(antiguaybarbuda,13).
proteccion_de_los_inversionistas_minoritarios(belice,17).
proteccion_de_los_inversionistas_minoritarios(barbados,28).
proteccion_de_los_inversionistas_minoritarios(brasil,2).
proteccion_de_los_inversionistas_minoritarios(guyana,15).
proteccion_de_los_inversionistas_minoritarios(nicaragua,25).
proteccion_de_los_inversionistas_minoritarios(bahamas,18).
proteccion_de_los_inversionistas_minoritarios(sanvicenteylasgranadinas,11).
proteccion_de_los_inversionistas_minoritarios(sankittsynevis,16).
proteccion_de_los_inversionistas_minoritarios(grenada,20).
proteccion_de_los_inversionistas_minoritarios(bolivia,23).
proteccion_de_los_inversionistas_minoritarios(suriname,27).
proteccion_de_los_inversionistas_minoritarios(haiti,32).
proteccion_de_los_inversionistas_minoritarios(venezuela,31).

% Pago de impuestos

pago_de_impuestos(mexico,9).
pago_de_impuestos(peru,2).
pago_de_impuestos(colombia,20).
pago_de_impuestos(puertorico,18).
pago_de_impuestos(jamaica,3).
pago_de_impuestos(costarica,8).
pago_de_impuestos(panama,28).
pago_de_impuestos(guatemala,1).
pago_de_impuestos(santalucia,7).
pago_de_impuestos(uruguay,13).
pago_de_impuestos(elsalvador,21).
pago_de_impuestos(trinidadytobago,16).
pago_de_impuestos(republicadominicana,6).
pago_de_impuestos(dominica,10).
pago_de_impuestos(paraguay,15).
pago_de_impuestos(honduras,25).
pago_de_impuestos(ecuador,22).
pago_de_impuestos(argentina,29).
pago_de_impuestos(antiguaybarbuda,26).
pago_de_impuestos(belice,4).
pago_de_impuestos(barbados,11).
pago_de_impuestos(brasil,30).
pago_de_impuestos(guyana,17).
pago_de_impuestos(nicaragua,27).
pago_de_impuestos(bahamas,14).
pago_de_impuestos(sanvicenteylasgranadinas,12).
pago_de_impuestos(sankittsynevis,24).
pago_de_impuestos(grenada,19).
pago_de_impuestos(bolivia,32).
pago_de_impuestos(suriname,5).
pago_de_impuestos(haiti,23).
pago_de_impuestos(venezuela,31).

% Comercio transfronterizo

comercio_transfronterizo(mexico,4).
comercio_transfronterizo(peru,14).
comercio_transfronterizo(colombia,23).
comercio_transfronterizo(puertorico,5).
comercio_transfronterizo(jamaica,27).
comercio_transfronterizo(costarica,6).
comercio_transfronterizo(panama,2).
comercio_transfronterizo(guatemala,10).
comercio_transfronterizo(santalucia,13).
comercio_transfronterizo(uruguay,29).
comercio_transfronterizo(elsalvador,1).
comercio_transfronterizo(trinidadytobago,24).
comercio_transfronterizo(republicadominicana,3).
comercio_transfronterizo(dominica,12).
comercio_transfronterizo(paraguay,22).
comercio_transfronterizo(honduras,19).
comercio_transfronterizo(ecuador,16).
comercio_transfronterizo(argentina,21).
comercio_transfronterizo(antiguaybarbuda,20).
comercio_transfronterizo(belice,18).
comercio_transfronterizo(barbados,25).
comercio_transfronterizo(brasil,30).
comercio_transfronterizo(guyana,28).
comercio_transfronterizo(nicaragua,8).
comercio_transfronterizo(bahamas,31).
comercio_transfronterizo(sanvicenteylasgranadinas,15).
comercio_transfronterizo(sankittsynevis,7).
comercio_transfronterizo(grenada,26).
comercio_transfronterizo(bolivia,17).
comercio_transfronterizo(suriname,11).
comercio_transfronterizo(haiti,9).
comercio_transfronterizo(venezuela,32).

% Resolucion de insolvencia

resolucion_de_la_insolvencia(mexico,2).
resolucion_de_la_insolvencia(peru,10).
resolucion_de_la_insolvencia(colombia,3).
resolucion_de_la_insolvencia(puertorico,1).
resolucion_de_la_insolvencia(jamaica,5).
resolucion_de_la_insolvencia(costarica,17).
resolucion_de_la_insolvencia(panama,22).
resolucion_de_la_insolvencia(guatemala,24).
resolucion_de_la_insolvencia(santalucia,18).
resolucion_de_la_insolvencia(uruguay,7).
resolucion_de_la_insolvencia(elsalvador,11).
resolucion_de_la_insolvencia(trinidadytobago,9).
resolucion_de_la_insolvencia(republicadominicana,27).
resolucion_de_la_insolvencia(dominica,20).
resolucion_de_la_insolvencia(paraguay,15).
resolucion_de_la_insolvencia(honduras,23).
resolucion_de_la_insolvencia(ecuador,26).
resolucion_de_la_insolvencia(argentina,14).
resolucion_de_la_insolvencia(antiguaybarbuda,19).
resolucion_de_la_insolvencia(belice,12).
resolucion_de_la_insolvencia(barbados,4).
resolucion_de_la_insolvencia(brasil,8).
resolucion_de_la_insolvencia(guyana,25).
resolucion_de_la_insolvencia(nicaragua,16).
resolucion_de_la_insolvencia(bahamas,6).
resolucion_de_la_insolvencia(sanvicenteylasgranadinas,29).
resolucion_de_la_insolvencia(sankittsynevis,32).
resolucion_de_la_insolvencia(grenada,31).
resolucion_de_la_insolvencia(bolivia,13).
resolucion_de_la_insolvencia(suriname,21).
resolucion_de_la_insolvencia(haiti,30).
resolucion_de_la_insolvencia(venezuela,28).




